inherit_from: .rubocop_todo.yml

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/Encoding:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 250

Metrics/AbcSize:
  Max: 25
