distro: xenial
cache: bundler
language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.3
  - 3.0.0
  - 3.1.0

before_install:
  - gem update bundler

# This prevents testing branches that are created just for PRs
branches:
  only:
  - master
